twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'

knp_paginator:
    template:
        pagination: '_pagination.twig'

when@test:
    twig:
        strict_variables: true
